name: Deploy Java application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: latest
      - run: gcloud auth configure-docker --quiet
      - run: docker build -t gcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }} .
      - run: docker push gcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
      - run: gcloud compute instances create my-instance \
          --image-family=debian-11 \
          --image-project=debian-cloud \
          --machine-type=e2-standard-4 \
          --scopes cloud-platform \
          --metadata-from-file startup-script=startup-script.sh \
          --metadata google-docker-registry=gcr.io \
          --metadata google-docker-image=${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
