runtime: java
env: flex
runtime_config:
  jdk: openjdk11
handlers:
  - url: /.*
    script: auto
manual_scaling:
  instances: 1
# network:
#   instance_tag: private-service 

# runtime: java11
# handlers:
#   - url: /.*
#     script: auto
# network:
#   name: projects/midyear-byway-418606/global/networks/wine-park-vpc
#   instance_tag: private-service
