# runtime: custom
# env: flex
# service: api

# runtime_config:
#    jdk: openjdk:11

# handlers:
# - url: /.*
#   # script: this field is required, but ignored

# automatic_scaling:
#   min_num_instances: 1


# runtime: custom
# env: flex

# runtime_config:
#   jdk:'openjdk11'
# handlers:
# - url: .*
#   # script: this field is required, but ignored

# automatic_scaling:
#   min_instances: 1

# runtime: custom
# env: flex
# runtime_config:
#    jdk:'openjdk11'
