runtime: java
env: flex
runtime_config:
  jdk: openjdk11
handlers:
  - url: /.*
    script: auto
network:
  name: projects/midyear-byway-418606/global/networks/wine-park-vpc
  subnetwork_name: projects/midyear-byway-418606/regions/us-central1/subnetworks/servicenetworking-googleapis-com
  egress_settings: PRIVATE_RANGES_ONLY
manual_scaling:
  instances: 1
