steps:
  # Step 3: Build the Maven project
  - name: 'maven:3-eclipse-temurin-11-alpine'
    entrypoint: 'mvn'
    args: ['clean', 'install','Dmaven.test.ignore=true']

  # Step 5: Containerize APP
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/midyear-byway-418606/wine-park-artifact-repo/wine-park-image:$SHORT_SHA', '.']

  # Step 6: Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/midyear-byway-418606/wine-park-artifact-repo/wine-park-image:$SHORT_SHA']

  # Step 7: Deploy GAR image to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--image-url', 'us-central1-docker.pkg.dev/midyear-byway-418606/wine-park-artifact-repo/wine-park-image:$SHORT_SHA']

images:
  - 'us-central1-docker.pkg.dev/midyear-byway-418606/wine-park-artifact-repo/wine-park-image:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY



