steps:
 #  Step 1: Git Clone
 # - name: 'gcr.io/cloud-builders/git'
 #   args: ['clone', 'https://github.com/yuktaakhade/wine-park.git', 'source']

#  # Step 2: Check Maven Version & Run Unit Tests
#  - name: 'maven:3'
#    entrypoint: 'mvn'
#    args: ['test']
#
  # Step 3: Build the Maven project
  - name: 'maven:3'
    entrypoint: 'mvn'
    args: ['clean', 'install']

  # Step 4: Containerize APP
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/midyear-byway-418606/wine-park:$SHORT_SHA', '.' ]

options:
  logging: CLOUD_LOGGING_ONLY
