FROM openjdk:11
ARG MYSQL_HOST_WITH_PORT
ARG MYSQL_DB_NAME
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ENV MYSQL_HOST_WITH_PORT=$MYSQL_HOST_WITH_PORT
ENV MYSQL_DB_NAME=$MYSQL_DB_NAME
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
COPY target/wine-park-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
